README: add ./generate.py instructions
saleemrashid/is-this-a-pigeon pull request #2
Opened 2018-07-05 11:59 UTC by lucaswerkmeister

Since Twitter suspended @this_pigeon (:sob:), I figure these instructions are useful. (I’m not sure if the example message is ideal, though… perhaps we need to tone down the salt ;) )

2018-07-05 12:37 UTC, saleemrashid commented
Thanks for the pull request! Since that functionality was originally added for debug purposes, it might be an idea to rewrite that to `argparse` and add a `-o/--output` and a `--open` option before documenting it?

2018-07-05 13:23 UTC, lucaswerkmeister commented
Good point, done. (I changed the `--open` to `--view` so that it could have a short option, is that okay?)

2018-07-05 15:44 UTC, saleemrashid requested changes
Would it be possible to make those two changes and switch all the single quotes to double quotes, for consistency?

Thanks for all the work!

2018-07-05 15:44 UTC, saleemrashid commented on README.md
> +./generate.py Twitter admins: is @this_pigeon bad?
Could you quote this? (as some shells will expand the `?` as a glob)

2018-07-05 15:44 UTC, saleemrashid commented on generate.py
> +    parser = argparse.ArgumentParser(description='Generate an Is This A Pigeon? image.', epilog='Example: ./generate.py me: Is \\"a single example\\" good documentation?')
Not sure about the `description` and `epilog`. Could we leave this blank for now?

2018-07-05 16:18 UTC, lucaswerkmeister commented
Sure, no problem! :)

2018-07-06 15:25 UTC, saleemrashid approved these changes

2018-07-06 15:25 UTC, merged

2018-07-06 15:25 UTC, saleemrashid commented
Thanks!

2018-07-06 18:24 UTC, lucaswerkmeister commented
No problem, thank you for writing this :)